---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: flux-system
spec:
  releaseName: headlamp
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: headlamp
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
