apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: keda
spec:
  releaseName: keda
  targetNamespace: keda
  interval: 30m
  dependsOn:
    - name: aws-load-balancer-controller
      namespace: flux-system
    - name: metrics-server
      namespace: flux-system
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: SA_SQS_KEDA_IAM_ROLE_ARN
