---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter-crd
  namespace: flux-system
spec:
  releaseName: karpenter-crd
  interval: 30m
  dependsOn:
    - name: aws-load-balancer-controller
      namespace: flux-system
    - name: metrics-server
      namespace: flux-system
  chart:
    spec:
      chart: karpenter-crd
      version: "1.8.1"
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: flux-system
  targetNamespace: karpenter
  install:
    crds: CreateReplace
    remediation:
      retries: 3
