---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  releaseName: karpenter
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: karpenter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: karpenter
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nodeSelector:
      karpenter.sh/controller: 'true'
    settings:
      clusterName: eks-keda-sqs-lab
      interruptionQueue: Karpenter-eks-keda-sqs-lab
