---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: karpenter
  namespace: flux-system
spec:
  interval: 24h
  url: oci://public.ecr.aws/karpenter/karpenter
  ref:
    tag: v1.8
