{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    name: {{ .Values.serviceAccount.name }}
    app.kubernetes.io/name: {{ .Values.serviceAccount.name | quote }}
    {{- include "sqs-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end -}}
