---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  releaseName: external-dns
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/eks-keda-sqs-lab-external-dns-20251010205622366000000005
    region: us-west-2
    clusterName: eks-keda-sqs-lab
    domainFilters: ["dallin.brewsentry.com"]
    policy: upsert-only
