---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: flux-system
spec:
  releaseName: cluster-autoscaler
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: cluster-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    autoDiscovery:
      clusterName: eks-keda-sqs-lab
    awsRegion: us-west-2
    cloudProvider: aws
    rbac:
      serviceAccount:
        create: true
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::704855531002:role/eks-keda-sqs-lab-cluster-autoscaler-20251010205622970800000008
    replicaCount: 2
